version: '3.7'


services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    env_file: .env
    volumes:
      - ./db-data:/var/lib/mysql:delegated
    ports:
      - "3306:3306"
    networks:
      - internal

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .env
    command: >
      sh -c "python manage.py migrate && gunicorn core.wsgi:app --bind 0.0.0.0:8000 --reload"
    expose:
      - 8000
    volumes:
      - ./src:/app:delegated
    depends_on:
      - mysql
    networks:
      - internal

  nginx:
    image: nginx:1.28-alpine
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - '80:80'
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  static:
