# Generated by Django 4.2.17 on 2025-05-29 18:41

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.CharField(max_length=36, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('document_number', models.CharField(max_length=50)),
                ('document_date', models.DateTimeField()),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organizations')),
            ],
        ),
    ]
